### PR TITLE
wip(buildtools): add nightwatchjs tests with saucelabs

### PR DESCRIPTION
**Pull request by derchrisuk**
This will implement NightWatchJS End-to-End tests written in NodeJS.
They can either run against a local, or what is the aim of this, against a SauceLabs Selenium server.
We currently have an unlimited testing account,can run 3 tests in parallel, and I already included config for several browser/os combinations:

ff win7
chrome win7
safari win7
ie win7
ff mac
chrome mac
safari mac
iphone
ipad
nexus7hd
samsungs4

With this we will get a browser support matrix like this:

[Sauce Test Status](https://saucelabs.com/u/derchris)

Included in this is also a grunt-concurrent plugin to run some tests in parallel too.
This should only be run with CodeShip builds, as the list of test suites to use is in an ENV.

There are currently 2x test for a simple google search for webspell, and check results, both for CSS and Xpath selector.

Still WIP, currently looking at a good way to not have it run on every build, just on request.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/webSPELL/webSPELL/pull/203%23issuecomment-73786845%22%2C%20%22https%3A//github.com/webSPELL/webSPELL/pull/203%23issuecomment-75587699%22%2C%20%22https%3A//github.com/webSPELL/webSPELL/pull/203%23issuecomment-75832381%22%2C%20%22https%3A//github.com/webSPELL/webSPELL/pull/203%23issuecomment-76215171%22%2C%20%22https%3A//github.com/webSPELL/webSPELL/pull/203%23issuecomment-76280787%22%2C%20%22https%3A//github.com/webSPELL/webSPELL/pull/203%23issuecomment-76282800%22%2C%20%22https%3A//github.com/webSPELL/webSPELL/pull/203%23issuecomment-76364754%22%2C%20%22https%3A//github.com/webSPELL/webSPELL/pull/203%23issuecomment-76381000%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/webSPELL/webSPELL/pull/203%23issuecomment-73786845%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Test%20will%20only%20run%20if%20%27--nightwatch%27%20is%20added%20to%20commit%20message.%5Cr%5CnNow%20what%20other%20browser/os%20combinations%20should%20be%20added%3F%22%2C%20%22created_at%22%3A%20%222015-02-10T21%3A25%3A12Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/706758%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/derchrisuk%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222015-02-23T17%3A19%3A40Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/498197%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Pascalmh%22%7D%7D%2C%20%7B%22body%22%3A%20%22Need%20to%20add%20a%20way%20to%20have%20the%20current%20branch%20push%20to%20a%20new%20subdomain%20to%20be%20used%20for%20testing%22%2C%20%22created_at%22%3A%20%222015-02-24T19%3A53%3A49Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/706758%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/derchrisuk%22%7D%7D%2C%20%7B%22body%22%3A%20%22Whatever%20branch%20has%20%60--nightwatch%60%20in%20the%20commit%20message%20will%20now%20be%20deployed%20to%20a%20subdomain%20which%20will%20be%20used%20for%20the%20E2E%20tests.%5Cr%5CnI%20only%20need%20to%20setup%20a%20basic%20DB%20for%20the%20subdomain%2C%20and%20then%20we%20can%20add%20tests%20for%20it.%22%2C%20%22created_at%22%3A%20%222015-02-26T16%3A50%3A19Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/706758%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/derchrisuk%22%7D%7D%2C%20%7B%22body%22%3A%20%22Subdomain%20is%20ready%2C%20DB%20setup.%5Cr%5CnI%20though%20about%20another%20method%20for%20running%20test.%5Cr%5CnInstead%20of%20using%20%60--nightwatch%60%2C%20we%20could%20just%20use%20the%20test%20type%20for%20it.%5Cr%5CnI%20could%20even%20use%20both%20the%20type%20and%20scope%20to%20tag%20the%20tests.%22%2C%20%22created_at%22%3A%20%222015-02-26T21%3A45%3A17Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/706758%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/derchrisuk%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222015-02-26T21%3A56%3A41Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/706758%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/derchrisuk%22%7D%7D%2C%20%7B%22body%22%3A%20%22%60/tools/%60%20%20should%20have%20a%20subfolder%20%60/nightwatchjs%60/%20where%20all%20the%20stuff%20should%20be%20located%2C%20same%20with%20%60/tests/%60%22%2C%20%22created_at%22%3A%20%222015-02-27T09%3A45%3A51Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/498197%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Pascalmh%22%7D%7D%2C%20%7B%22body%22%3A%20%22Test%20is%20now%20running%20either%20with%20test%20type%20or%20--nightwatch.%5Cr%5CnMerge%20as%20it%20is%2C%20and%20will%20implement%20more%20tests%20and%20a%20way%20to%20grab%20the%20scope%20of%20test%20type%2C%20and%20add%20as%20tag%20to%20test%20report.%22%2C%20%22created_at%22%3A%20%222015-02-27T11%3A28%3A22Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/706758%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/derchrisuk%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22approved%22%3A%20%7B%22https%3A//github.com/Pascalmh%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/498197%3Fv%3D3%22%7D%2C%20%22https%3A//github.com/derchrisuk%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/706758%3Fv%3D3%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>

<a href='https://github.com/Pascalmh'></a><a href='https://github.com/derchrisuk'></a>

- [x] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/webSPELL/webSPELL/pull/203#issuecomment-73786845'>General Comment</a></b>
- <a href='https://github.com/derchrisuk'></a> Test will only run if '--nightwatch' is added to commit message.
Now what other browser/os combinations should be added?
- <a href='https://github.com/Pascalmh'></a> :shipit:
- <a href='https://github.com/derchrisuk'></a> Need to add a way to have the current branch push to a new subdomain to be used for testing
- <a href='https://github.com/derchrisuk'></a> Whatever branch has `--nightwatch` in the commit message will now be deployed to a subdomain which will be used for the E2E tests.
I only need to setup a basic DB for the subdomain, and then we can add tests for it.
- <a href='https://github.com/derchrisuk'></a> Subdomain is ready, DB setup.
I though about another method for running test.
Instead of using `--nightwatch`, we could just use the test type for it.
I could even use both the type and scope to tag the tests.
- <a href='https://github.com/derchrisuk'></a> :shipit:
- <a href='https://github.com/Pascalmh'></a> `/tools/`  should have a subfolder `/nightwatchjs`/ where all the stuff should be located, same with `/tests/`
- <a href='https://github.com/derchrisuk'></a> Test is now running either with test type or --nightwatch.
Merge as it is, and will implement more tests and a way to grab the scope of test type, and add as tag to test report.

<a href='https://www.codereviewhub.com/webSPELL/webSPELL/pull/203?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/webSPELL/webSPELL/pull/203?approve=1'></a>&nbsp;<a href='https://www.codereviewhub.com/webSPELL/webSPELL/pull/203?approve=0'></a>&nbsp;<a href='https://github.com/webSPELL/webSPELL/pull/203'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by derchrisuk** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/webSPELL/webSPELL/pull/203'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by derchrisuk** [comment]
Test will only run if '--nightwatch' is added to commit message.
Now what other browser/os combinations should be added?

**Comment by Pascalmh** [comment]
:shipit:

**Comment by derchrisuk** [comment]
Need to add a way to have the current branch push to a new subdomain to be used for testing

**Comment by derchrisuk** [comment]
Whatever branch has `--nightwatch` in the commit message will now be deployed to a subdomain which will be used for the E2E tests.
I only need to setup a basic DB for the subdomain, and then we can add tests for it.

**Comment by derchrisuk** [comment]
Subdomain is ready, DB setup.
I though about another method for running test.
Instead of using `--nightwatch`, we could just use the test type for it.
I could even use both the type and scope to tag the tests.

**Comment by derchrisuk** [comment]
:shipit:

**Comment by Pascalmh** [comment]
`/tools/`  should have a subfolder `/nightwatchjs`/ where all the stuff should be located, same with `/tests/`

**Comment by derchrisuk** [comment]
Test is now running either with test type or --nightwatch.
Merge as it is, and will implement more tests and a way to grab the scope of test type, and add as tag to test report.

**Pull request merged**
