### PR TITLE
feat(admincenter): add sc_demos/files list sorting to settings

### LINKED ISSUE #165: sc_demos/sc_files - put Option into Admincenter
https://github.com/webSPELL/webSPELL-4.2.3/blob/265f12fdca099ee8f219a2fc48451adbdd2004e8/sc_demos.php#L30 this Option should be available in the Admincenter

### PR DESCRIPTION
**Pull request by derchrisuk**
This will fix #165
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/webSPELL/webSPELL/pull/206%23issuecomment-73979252%22%2C%20%22https%3A//github.com/webSPELL/webSPELL/pull/206%23issuecomment-74039975%22%2C%20%22https%3A//github.com/webSPELL/webSPELL/pull/206%23issuecomment-75444238%22%2C%20%22https%3A//github.com/webSPELL/webSPELL/pull/206%23issuecomment-75444371%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/webSPELL/webSPELL/pull/206%23issuecomment-73979252%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Aren%27t%20there%20new%20Database%20fields%3F%20Do%20we%20have%20to%20add%20stuff%20to%20the%20installation%3F%22%2C%20%22created_at%22%3A%20%222015-02-11T22%3A31%3A17Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/498197%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Pascalmh%22%7D%7D%2C%20%7B%22body%22%3A%20%22Yes.%20I%20left%20out%20the%20install%20for%20now%20because%20of%20the%20changes%20in%20install_poc%5Cr%5CnOnly%202x%20new%20items%20in%20settings%20are%20needed.%22%2C%20%22created_at%22%3A%20%222015-02-12T09%3A18%3A21Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/706758%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/derchrisuk%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3A%2B1%3A%22%2C%20%22created_at%22%3A%20%222015-02-22T16%3A44%3A34Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/498197%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Pascalmh%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222015-02-22T16%3A47%3A28Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/498197%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Pascalmh%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22approved%22%3A%20%7B%22https%3A//github.com/Pascalmh%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/498197%3Fv%3D3%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>

<a href='https://github.com/Pascalmh'></a>

- [x] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/webSPELL/webSPELL/pull/206#issuecomment-73979252'>General Comment</a></b>
- <a href='https://github.com/Pascalmh'></a> Aren't there new Database fields? Do we have to add stuff to the installation?
- <a href='https://github.com/derchrisuk'></a> Yes. I left out the install for now because of the changes in install_poc
Only 2x new items in settings are needed.

<a href='https://www.codereviewhub.com/webSPELL/webSPELL/pull/206?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/webSPELL/webSPELL/pull/206?approve=1'></a>&nbsp;<a href='https://www.codereviewhub.com/webSPELL/webSPELL/pull/206?approve=0'></a>&nbsp;<a href='https://github.com/webSPELL/webSPELL/pull/206'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by webSPELL-org** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/webSPELL/webSPELL/pull/206'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by Pascalmh** [comment]
Aren't there new Database fields? Do we have to add stuff to the installation?

**Comment by derchrisuk** [comment]
Yes. I left out the install for now because of the changes in install_poc
Only 2x new items in settings are needed.

**Comment by Pascalmh** [comment]
:+1:

**Comment by Pascalmh** [comment]
:shipit:

**Pull request merged**
