### PR TITLE
fix(register): fix register adaptation

### PR DESCRIPTION
**Pull request by xxxrenegade**
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/webSPELL/webSPELL/pull/214%23issuecomment-82566533%22%2C%20%22https%3A//github.com/webSPELL/webSPELL/pull/214%23issuecomment-85623033%22%2C%20%22https%3A//github.com/webSPELL/webSPELL/pull/214%23issuecomment-85627890%22%2C%20%22https%3A//github.com/webSPELL/webSPELL/pull/214%23issuecomment-85652465%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/webSPELL/webSPELL/pull/214%23issuecomment-82566533%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22There%20is%20a%20newline%20%28lf%29%20missing%20at%20end%20of%20file.%5Cr%5CnApart%20from%20that%20looks%20good.%22%2C%20%22created_at%22%3A%20%222015-03-17T19%3A48%3A04Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/706758%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/derchrisuk%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%5Cr%5Cnthank%20you%20%3B%29%22%2C%20%22created_at%22%3A%20%222015-03-24T18%3A01%3A35Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1415280%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Phhere%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%20%22%2C%20%22created_at%22%3A%20%222015-03-24T18%3A11%3A53Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/498197%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Pascalmh%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222015-03-24T19%3A16%3A02Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/706758%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/derchrisuk%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22approved%22%3A%20%7B%22https%3A//github.com/Pascalmh%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/498197%3Fv%3D3%22%7D%2C%20%22https%3A//github.com/derchrisuk%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/706758%3Fv%3D3%22%7D%2C%20%22https%3A//github.com/Phhere%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1415280%3Fv%3D3%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>

<a href='https://github.com/Pascalmh'></a><a href='https://github.com/derchrisuk'></a><a href='https://github.com/Phhere'></a>

- [x] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/webSPELL/webSPELL/pull/214#issuecomment-82566533'>General Comment</a></b>
- <a href='https://github.com/derchrisuk'></a> There is a newline (lf) missing at end of file.
Apart from that looks good.
- <a href='https://github.com/Phhere'></a> :shipit:
thank you ;)

<a href='https://www.codereviewhub.com/webSPELL/webSPELL/pull/214?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/webSPELL/webSPELL/pull/214?approve=1'></a>&nbsp;<a href='https://www.codereviewhub.com/webSPELL/webSPELL/pull/214?approve=0'></a>&nbsp;<a href='https://github.com/webSPELL/webSPELL/pull/214'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by webSPELL-org** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/webSPELL/webSPELL/pull/214'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by derchrisuk** [comment]
There is a newline (lf) missing at end of file.
Apart from that looks good.

**Comment by Phhere** [comment]
:shipit:
thank you ;)

**Comment by Pascalmh** [comment]
:shipit:

**Comment by derchrisuk** [comment]
:shipit:

**Pull request merged**
