### PR TITLE
fix(links): fix links adaptation

### PR DESCRIPTION
**Pull request by xxxrenegade**
<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/derchrisuk%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/706758%3Fv%3D3%22%7D%2C%20%22https%3A//github.com/Phhere%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1415280%3Fv%3D3%22%7D%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/webSPELL/webSPELL/pull/217%23issuecomment-87768200%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222015-03-30T17%3A46%3A53Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1415280%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Phhere%22%7D%7D%2C%20%7B%22body%22%3A%20%22Why%20remove%20the%20value%20from%20templates/links_new.html%20in%20L34%3F%22%2C%20%22created_at%22%3A%20%222015-03-31T12%3A41%3A13Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/706758%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/derchrisuk%22%7D%7D%2C%20%7B%22body%22%3A%20%22Weil%20es%20einen%20W3C%20HTML5%20Error%20erzeugt%3A%5Cr%5Cn%5Cr%5CnBad%20value%20http%3A//%20for%20attribute%20value%20on%20element%20input%3A%20Invalid%20host%3A%20empty%20host.%5Cr%5Cn%5Cr%5Cn%3Cinput%20type%3D%5C%22url%5C%22%20name%3D%5C%22url%5C%22%20class%3D%5C%22form-control%5C%22%20id%3D%5C%22input-url%5C%22%20value%3D%5C%22http%3A//%5C%22%3E%5Cr%5Cn%5Cr%5CnSyntax%20of%20absolute%20URL%3A%5Cr%5CnAn%20absolute%20URL.%20For%20example%3A%20http%3A//example.org/hello%2C%20but%20not%20/hello.%20Spaces%20should%20be%20escaped%20as%20%2520.%5Cr%5Cn%5Cr%5Cn%22%2C%20%22created_at%22%3A%20%222015-03-31T14%3A07%3A56Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/2109906%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/xxxrenegade%22%7D%7D%2C%20%7B%22body%22%3A%20%22Change%20value%20to%20placeholder%2C%20as%20that%27s%20what%20it%20is%20meant%20for.%22%2C%20%22created_at%22%3A%20%222015-03-31T14%3A24%3A14Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/706758%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/derchrisuk%22%7D%7D%2C%20%7B%22body%22%3A%20%22I%20just%20committed%20a%20fix%20for%20the%20failing%20JS%20errors.%5Cr%5CnMerge%20the%20changes%20from%20dev%20into%20the%20PR%2C%20then%20it%20should%20be%20good%20to%20merge.%22%2C%20%22created_at%22%3A%20%222015-03-31T16%3A29%3A20Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/706758%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/derchrisuk%22%7D%7D%2C%20%7B%22body%22%3A%20%22Das%20mit%20git%20%5Cu00fcben%20wir%20nochmal%20%3B%29%22%2C%20%22created_at%22%3A%20%222015-03-31T17%3A31%3A34Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/706758%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/derchrisuk%22%7D%7D%2C%20%7B%22body%22%3A%20%22Jo%20%5E%5E%22%2C%20%22created_at%22%3A%20%222015-03-31T17%3A33%3A09Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/2109906%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/xxxrenegade%22%7D%7D%2C%20%7B%22body%22%3A%20%22done%22%2C%20%22created_at%22%3A%20%222015-03-31T17%3A56%3A46Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/2109906%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/xxxrenegade%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222015-03-31T18%3A06%3A20Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/706758%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/derchrisuk%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22processed%22%3A%20%5B%22https%3A//github.com/webSPELL/webSPELL/pull/217%23issuecomment-87768200%22%2C%20%22https%3A//github.com/webSPELL/webSPELL/pull/217%23issuecomment-88069722%22%2C%20%22https%3A//github.com/webSPELL/webSPELL/pull/217%23issuecomment-88100934%22%2C%20%22https%3A//github.com/webSPELL/webSPELL/pull/217%23issuecomment-88107713%22%2C%20%22https%3A//github.com/webSPELL/webSPELL/pull/217%23issuecomment-88160147%22%2C%20%22https%3A//github.com/webSPELL/webSPELL/pull/217%23issuecomment-88179960%22%2C%20%22https%3A//github.com/webSPELL/webSPELL/pull/217%23issuecomment-88180332%22%2C%20%22https%3A//github.com/webSPELL/webSPELL/pull/217%23issuecomment-88188304%22%2C%20%22https%3A//github.com/webSPELL/webSPELL/pull/217%23issuecomment-88191811%22%5D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>

<a href='https://github.com/derchrisuk'></a><a href='https://github.com/Phhere'></a>

- [x] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/webSPELL/webSPELL/pull/217#issuecomment-87768200'>General Comment</a></b>
- <a href='https://github.com/Phhere'></a> :shipit:
- <a href='https://github.com/derchrisuk'></a> Why remove the value from templates/links_new.html in L34?
- <a href='https://github.com/xxxrenegade'></a> Weil es einen W3C HTML5 Error erzeugt:
Bad value http:// for attribute value on element input: Invalid host: empty host.
<input type="url" name="url" class="form-control" id="input-url" value="http://">
Syntax of absolute URL:
An absolute URL. For example: http://example.org/hello, but not /hello. Spaces should be escaped as %20.
- <a href='https://github.com/derchrisuk'></a> Change value to placeholder, as that's what it is meant for.
- <a href='https://github.com/derchrisuk'></a> I just committed a fix for the failing JS errors.
Merge the changes from dev into the PR, then it should be good to merge.
- <a href='https://github.com/derchrisuk'></a> Das mit git üben wir nochmal ;)
- <a href='https://github.com/xxxrenegade'></a> Jo ^^
- <a href='https://github.com/xxxrenegade'></a> done

<a href='https://www.codereviewhub.com/webSPELL/webSPELL/pull/217?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/webSPELL/webSPELL/pull/217?approve=1'></a>&nbsp;<a href='https://www.codereviewhub.com/webSPELL/webSPELL/pull/217?approve=0'></a>&nbsp;<a href='https://github.com/webSPELL/webSPELL/pull/217'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by webSPELL-org** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/webSPELL/webSPELL/pull/217'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by Phhere** [comment]
:shipit:

**Comment by derchrisuk** [comment]
Why remove the value from templates/links_new.html in L34?

**Comment by xxxrenegade** [comment]
Weil es einen W3C HTML5 Error erzeugt:

Bad value http:// for attribute value on element input: Invalid host: empty host.

<input type="url" name="url" class="form-control" id="input-url" value="http://">

Syntax of absolute URL:
An absolute URL. For example: http://example.org/hello, but not /hello. Spaces should be escaped as %20.

**Comment by derchrisuk** [comment]
Change value to placeholder, as that's what it is meant for.

**Comment by derchrisuk** [comment]
I just committed a fix for the failing JS errors.
Merge the changes from dev into the PR, then it should be good to merge.

**Comment by derchrisuk** [comment]
Das mit git üben wir nochmal ;)

**Comment by xxxrenegade** [comment]
Jo ^^

**Comment by xxxrenegade** [comment]
done

**Comment by derchrisuk** [comment]
:shipit:

**Pull request merged**
